package tpl

const (
	Repository = `// Code generated by go-generator-test (cmd/generator/main.go). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.
//go:generate mockgen -source=$GOFILE -destination=mock_$GOPACKAGE/mock_$GOFILE
//go:generate goimports -w --local "github.com/iyu/go-generator-test" mock_$GOPACKAGE/mock_$GOFILE
{{ $name := .PkgName }}
package {{ $name }}

import (
	"context"

	"github.com/iyu/go-generator-test/pkg/domain/entity/{{ $name }}"
)

{{ range .Entities -}}
type {{ .Name }}Repository interface {
	Select(ctx context.Context) (*{{ $name }}.{{ .Name }}, error)
	Insert(ctx context.Context, entity *{{ $name }}.{{ .Name }}) error
	Update(ctx context.Context, entity *{{ $name }}.{{ .Name }}) error
	Delete(ctx context.Context, entity *{{ $name }}.{{ .Name }}) error
}
{{ end -}}
`
)
