// Code generated by go-generator-test (cmd/generator/main.go). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.
//go:generate mockgen -source=$GOFILE -destination=mock_$GOPACKAGE/mock_$GOFILE
//go:generate goimports -w --local "github.com/iyu/go-generator-test" mock_$GOPACKAGE/mock_$GOFILE

package user

import (
	"context"

	"github.com/iyu/go-generator-test/pkg/domain/entity/user"
)

type UserRepository interface {
	Select(ctx context.Context) (*user.User, error)
	Insert(ctx context.Context, entity *user.User) error
	Update(ctx context.Context, entity *user.User) error
	Delete(ctx context.Context, entity *user.User) error
}
